server:
  port: 8094
# 运用名
spring:
  application:
    name: boot-demo-client
  datasource:
      url: jdbc:mysql://:3306/bigdata?useUnicode=true&useSSL=true&characterEncoding=utf-8&allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
      username:
      password:
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        max-lifetime: 1800000
        connection-timeout: 30000
  # redis 配置
  redis:
    host:
    port:
    lettuce:
      pool:
        max-active: 200
        max-wait: 2000
        min-idle: 10
        max-idle: 200
# mybatis 配置文件
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
# 服务注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/