server:
  port: 8096
spring:
  application:
    name: zipkin-server
# 注册给注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false