server:
  port: 8011
  servlet:
    context-path: /uaa
spring:
  application:
    name: oauth-server
  security:
    oauth2:
      client:
        provider:
        registration:

# 注册服务
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/