server:
  port: 9090
spring:
  application:
    name: zuul-client

#服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
# 路由服务
zuul:
  routes:
    hello:
      # /** 是可以将所有的请求都可以过滤到该服务提供上 , 如果过滤具体的其他实例可以更改这个地址
      path: /**
      serviceId: eureka-client
  #版本号
  prefix: /v1

# 自己维护注册信息，不想 eureka-server获取注册信息



