server:
  port: 8099
spring:
  application:
    name: admin-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
logging:
  file: "./logs/client-log.log"
management:
  security:
    enabled: false