server:
  port: 8092
spring:
  application:
    name: feign-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

# 开启熔断器
feign:
  hystrix:
    enabled: true
#关闭验证
management:
  security:
    enabled: false
logging:
  file: "./logs/feign-client.log"
